services:
  - type: web
    name: job-portal
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://guptavarun132_db_user:dQH28u9L8Rru_9Q@chatapp.fwtcmjb.mongodb.net/jobportal?retryWrites=true&w=majority
      - key: PORT
        value: 10000
